site_name: Test Docs
site_url: https://ksurl.github.io/testdocs/
repo_url: https://github.com/ksurl/testdocs/
theme:
  name: 'material'
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
nav:
   - 'Home': 'index.md'
   - 'Test': 'test.md'
plugins:
    - search
